---

- name: Create Server and install docker
  import_playbook: linux_base_server.yml
  tags: [ spawn ]

- name: ROLE | Configure Hosts for Konvoy
  hosts: ["{{ variable_host }}:&worker"]
  gather_facts: true
  vars: 
    ansible_python_interpreter: python3
  roles:
    - role: ar_add_data_disk
      tags: [ ar_add_data_disk ]

#TODO: Ensure system in targeted mode
#TODO: Ensure swap off and references to in /etc/fstab removed
#TODO: Ensure firewalld disabled

#sudo systemctl stop firewalld && sudo systemctl disable firewalld
#sudo swapoff -a